"""initial schema

Revision ID: 0158449f4924
Revises: 
Create Date: 2026-09-19 17:41:17.274486
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0158449f4924'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('icp', sa.JSON(), nullable=False),
    sa.Column('agent_settings', sa.JSON(), nullable=False),
    sa.Column('channel_policies', sa.JSON(), nullable=False),
    sa.Column('default_channel_priority', sa.JSON(), nullable=False),
    sa.Column('system_prompt_version', sa.String(), nullable=True),
    sa.Column('assigned_rep_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppression_entries',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('agent_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('prompt_version_id', sa.String(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_decisions_campaign_id'), 'agent_decisions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_agent_decisions_prospect_id'), 'agent_decisions', ['prospect_id'], unique=False)
    op.create_table('campaign_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_assets_campaign_id'), 'campaign_assets', ['campaign_id'], unique=False)
    op.create_table('campaign_prospect_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('qualification_reasoning', sa.Text(), nullable=True),
    sa.Column('persona_id', sa.String(), nullable=True),
    sa.Column('human_approved', sa.Boolean(), nullable=False),
    sa.Column('human_approved_by', sa.String(), nullable=True),
    sa.Column('last_contacted_channel', sa.String(), nullable=True),
    sa.Column('contact_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_prospect_links_campaign_id'), 'campaign_prospect_links', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_prospect_links_prospect_id'), 'campaign_prospect_links', ['prospect_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('prompt_version_id', sa.String(), nullable=True),
    sa.Column('call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcript_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_campaign_id'), 'conversation_turns', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_prospect_id'), 'conversation_turns', ['prospect_id'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('qualification_notes', sa.Text(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('tone_notes', sa.Text(), nullable=True),
    sa.Column('channel_priority', sa.JSON(), nullable=False),
    sa.Column('templates', sa.JSON(), nullable=False),
    sa.Column('example_messages', sa.JSON(), nullable=False),
    sa.Column('follow_up_policy', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_campaign_id'), 'personas', ['campaign_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_campaign_id'), 'prompt_versions', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_versions_campaign_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_personas_campaign_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_conversation_turns_prospect_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_campaign_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_campaign_prospect_links_prospect_id'), table_name='campaign_prospect_links')
    op.drop_index(op.f('ix_campaign_prospect_links_campaign_id'), table_name='campaign_prospect_links')
    op.drop_table('campaign_prospect_links')
    op.drop_index(op.f('ix_campaign_assets_campaign_id'), table_name='campaign_assets')
    op.drop_table('campaign_assets')
    op.drop_index(op.f('ix_agent_decisions_prospect_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_campaign_id'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_table('suppression_entries')
    op.drop_table('prospects')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
