"""add choreography to campaigns

Revision ID: b3f7e1c9a2d4
Revises: e894621f2734
Create Date: 2026-09-21 10:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b3f7e1c9a2d4'
down_revision: Union[str, None] = 'e894621f2734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('choreography', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'choreography')
    # ### end Alembic commands ###