"""add sources and connector_configs to campaigns

Revision ID: c709a5502bee
Revises: 01673c627969
Create Date: 2026-09-20 17:48:01.979078
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c709a5502bee'
down_revision: Union[str, None] = '01673c627969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
