"""add users and campaign config fields

Revision ID: cad6a85178b1
Revises: f660bf075ebe
Create Date: 2026-09-20 13:33:47.201324
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cad6a85178b1'
down_revision: Union[str, None] = 'f660bf075ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('campaigns', sa.Column('vision_statement', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('budget', sa.Float(), nullable=True))
    op.add_column('campaigns', sa.Column('start_date', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('end_date', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('target_scale', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('pace_per_day', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('goals', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'goals')
    op.drop_column('campaigns', 'pace_per_day')
    op.drop_column('campaigns', 'target_scale')
    op.drop_column('campaigns', 'end_date')
    op.drop_column('campaigns', 'start_date')
    op.drop_column('campaigns', 'budget')
    op.drop_column('campaigns', 'vision_statement')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
