"""add follow-up scheduling fields

Revision ID: f660bf075ebe
Revises: 0158449f4924
Create Date: 2026-09-19 22:51:59.069340
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f660bf075ebe'
down_revision: Union[str, None] = '0158449f4924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_prospect_links', sa.Column('follow_up_owed', sa.Boolean(), nullable=False))
    op.add_column('campaign_prospect_links', sa.Column('next_follow_up_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_prospect_links', 'next_follow_up_at')
    op.drop_column('campaign_prospect_links', 'follow_up_owed')
    # ### end Alembic commands ###
